WITH
INSTALLATION_INFO AS 
	(SELECT WORKITEM_ID, START_INSTALL_DATE, INSTALL_CODE, FINISH_INSTALL_DATE, ENVIRONMENT, FINISH_COLLECT_DATE
    FROM V_PATCH_VERSION 
    WHERE PATCH_NAME NOT IN (SELECT EXCLUDED_BACKLOG FROM T_PIPE_EXCLUSION)
        AND START_INSTALL_DATE > TO_DATE('01.12.2016', 'DD.MM.YYYY')
        AND ENVIRONMENT IN ('INST', 'MT', 'SIT')
        AND (CODE_TYPE = 'TD ' OR CODE_TYPE = 'TD')
    ORDER BY START_INSTALL_DATE DESC),   

INST AS 
	(SELECT 
	WORKITEM_ID, MAX_FINISH_COLLECT_DATE AS FINISH_COLLECT_DATE, (MIN(START_INSTALL_DATE) - MAX_FINISH_COLLECT_DATE) AS INST_HITCH, MIN(START_INSTALL_DATE) AS MIN_START_INSTALL_DATE
	FROM
		(SELECT 
		WORKITEM_ID, START_INSTALL_DATE, MAX(FINISH_COLLECT_DATE) AS MAX_FINISH_COLLECT_DATE
		FROM INSTALLATION_INFO    
		WHERE ENVIRONMENT = 'INST'
		GROUP BY WORKITEM_ID, START_INSTALL_DATE   
		)
	GROUP BY WORKITEM_ID, MAX_FINISH_COLLECT_DATE),

MT AS 
	(SELECT WORKITEM_ID, FINISH_COLLECT_DATE, (MIN(MT_START_INSTALL_DATE) - MAX_INST_FINISH_INSTALL_DATE) AS MT_HITCH, MIN(MT_START_INSTALL_DATE) AS MT_START_INSTALL_DATE, MAX_INST_FINISH_INSTALL_DATE
	FROM
		(SELECT 
		MT_1.WORKITEM_ID, MT_1.FINISH_COLLECT_DATE, MT_1.START_INSTALL_DATE AS MT_START_INSTALL_DATE, MAX(INST_1.FINISH_INSTALL_DATE) AS MAX_INST_FINISH_INSTALL_DATE
		FROM 
			(SELECT WORKITEM_ID, FINISH_COLLECT_DATE, START_INSTALL_DATE FROM INSTALLATION_INFO    
	        WHERE ENVIRONMENT = 'MT'
	        ) MT_1
		JOIN 
			(SELECT WORKITEM_ID, FINISH_COLLECT_DATE, FINISH_INSTALL_DATE FROM INSTALLATION_INFO    
	        WHERE ENVIRONMENT = 'INST'
	        AND INSTALL_CODE = '0'
	        ) INST_1
		ON INST_1.WORKITEM_ID = MT_1.WORKITEM_ID
		AND INST_1.FINISH_COLLECT_DATE = MT_1.FINISH_COLLECT_DATE
		AND INST_1.FINISH_INSTALL_DATE < MT_1.START_INSTALL_DATE
		GROUP BY MT_1.WORKITEM_ID, MT_1.FINISH_COLLECT_DATE, MT_1.START_INSTALL_DATE)
	GROUP BY WORKITEM_ID, FINISH_COLLECT_DATE, MAX_INST_FINISH_INSTALL_DATE),

SIT AS 
	(SELECT WORKITEM_ID, FINISH_COLLECT_DATE, (MIN(SIT_START_INSTALL_DATE) - MAX_MT_FINISH_INSTALL_DATE) AS SIT_HITCH, MIN(SIT_START_INSTALL_DATE) AS SIT_START_INSTALL_DATE, MAX_MT_FINISH_INSTALL_DATE
	FROM
		(SELECT 
		SIT_1.WORKITEM_ID, SIT_1.FINISH_COLLECT_DATE, SIT_1.START_INSTALL_DATE AS SIT_START_INSTALL_DATE, MAX(MT_1.FINISH_INSTALL_DATE) AS MAX_MT_FINISH_INSTALL_DATE
		FROM 
			(SELECT WORKITEM_ID, FINISH_COLLECT_DATE, START_INSTALL_DATE FROM INSTALLATION_INFO    
	        WHERE ENVIRONMENT = 'SIT'
	        ) SIT_1
		JOIN 
			(SELECT WORKITEM_ID, FINISH_COLLECT_DATE, FINISH_INSTALL_DATE FROM INSTALLATION_INFO    
	        WHERE ENVIRONMENT = 'MT'
	        AND INSTALL_CODE = '0'
	        ) MT_1
		ON MT_1.WORKITEM_ID = SIT_1.WORKITEM_ID
		AND MT_1.FINISH_COLLECT_DATE = SIT_1.FINISH_COLLECT_DATE
		AND MT_1.FINISH_INSTALL_DATE < SIT_1.START_INSTALL_DATE
		GROUP BY SIT_1.WORKITEM_ID, SIT_1.FINISH_COLLECT_DATE, SIT_1.START_INSTALL_DATE)
	GROUP BY WORKITEM_ID, FINISH_COLLECT_DATE, MAX_MT_FINISH_INSTALL_DATE)

SELECT 
WORKITEM_ID, FINISH_COLLECT_DATE, INST_HITCH AS HITCH, MIN_START_INSTALL_DATE AS EVENT_DATE, 'BUILD_INST' AS ENV
FROM INST

UNION ALL
SELECT 
MT.WORKITEM_ID, MT.FINISH_COLLECT_DATE, MT.MT_HITCH AS HITCH, MT_START_INSTALL_DATE AS EVENT_DATE, 'INST_MT' AS ENV
FROM MT

UNION ALL
SELECT 
SIT.WORKITEM_ID, SIT.FINISH_COLLECT_DATE, SIT.SIT_HITCH AS HITCH, SIT_START_INSTALL_DATE AS EVENT_DATE, 'MT_SIT' AS ENV
FROM SIT

ORDER BY EVENT_DATE DESC;
